config/routes.rb
Rails.application.routes.draw do
  resources :registrations, only: %i[ new create ]

  resources :sessions, only: %i[ index new create destroy ]

  resources :passwords, param: :token

  namespace :identity do
    resources :profiles, param: :name, only: %i[ index show ]
    resources :accounts, only: %i[ show edit update ]
    resources :avatars,  only: %i[ edit update destroy ]
    resources :tags,     except: %i[ index show ]
  end

  post "chats/:guest", to: "chats#create", as: :create_chat
  resources :chats, only: %i[ index destroy ] do
    resources :messages, except: %i[ new show ]
  end

  root "chats#index"
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :user

  validates :content, presence: true

  after_save_commit :broadcast_message

  private

    def broadcast_message
      ChatChannel.broadcast_to(chat, { sender: user.name, message_id: id })
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_chat
  before_action :set_message, only: %i[ edit update destroy ]

  # GET /messages
  def index
    @participant = @chat.users.where.not(id: Current.user.id).first
    set_page_and_extract_portion_from @chat.messages.order(created_at: :desc), per_page: 30

    sleep 4.seconds unless @page.first?
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  def create
    @message = @chat.messages.build(message_params)
    @message.user_id = Current.user.id

    if @message.save
      @message.broadcast_prepend_to(@chat, partial: "messages/message", locals: { chat: @chat, message: @message })
      update_form_with_turbo_stream
    end
  end

  # PATCH/PUT /messages/1
  def update
    if @message.update(message_params)
      @message.broadcast_replace_to(@chat, target: "message_#{@message.id}", partial: "messages/message", locals: { chat: @chat, message: @message })
      update_form_with_turbo_stream
    end
  end

  # DELETE /messages/1
  def destroy
    @message.destroy!
    @message.broadcast_remove_to(@chat, target: "message_#{@message.id}")
    update_form_with_turbo_stream
  end

  private
    def update_form_with_turbo_stream
       render turbo_stream: turbo_stream.update("new_message", partial: "messages/form", locals: { chat: @chat, message: @chat.messages.build })
    end

    def set_chat
      @chat = Chat.find(params[:chat_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = @chat.messages.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.expect(message: [ :content ])
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_with(model: [chat, message], class: "mt-2") do |form| %>
    <div class="relative">
        <%= form.text_area :content, rows: 1, class: "scroll pl-4 pr-14 py-3.5 w-full bg-white block shadow-sm rounded-full border border-gray-300 focus:outline-blue-600 dark:bg-slate-600 overflow-auto resize-none", placeholder: "Your message..." %>

        <div class="absolute bottom-2 right-2">
            <%= button_tag type: "submit", class: "rounded-full px-3.5 py-3.5 bg-blue-600 text-white font-medium cursor-pointer" do %>
                <svg class="w-3 h-3 rotate-90 rtl:-rotate-90" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 20">
                    <path d="m17.914 18.594-8-18a1 1 0 0 0-1.828 0l-8 18a1 1 0 0 0 1.157 1.376L8 18.281V9a1 1 0 0 1 2 0v9.281l6.758 1.689a1 1 0 0 0 1.156-1.376Z"/>
                </svg>
            <% end %>
        </div>
    </div>
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>" class="my-2 <%= 'flex justify-end' if message.user_id == Current.user.id %>">
  <div id="message" class="inline-flex rounded-lg p-2 <%= message.user_id == Current.user.id ? 'bg-slate-200 dark:bg-slate-800' : 'bg-indigo-100 dark:bg-slate-600' %>">
    <p class="max-w-[15rem] md:max-w-[35rem] break-words">
      <%= message.content %>
    </p>
    <%= link_to 'Edit', edit_chat_message_path(chat, message), data: { turbo_frame: 'new_message' }, class: "mt-auto ml-2 text-purple-600 text-xs" if message.user_id == Current.user.id %>
  </div>
</div>

app/views/messages/_next_page_container.html.erb
<%= turbo_frame_tag :next_page_container, loading: :lazy, src: chat_messages_path(chat: @chat, page: page, format: :turbo_stream), class: "flex justify-center my-4" do %>
    <svg aria-hidden="true" class="mt-6 inline w-8 h-8 text-gray-200 animate-spin dark:text-white fill-indigo-600" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"/>
        <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"/>
    </svg>
  <span class="sr-only">Loading...</span>
<% end %>

app/views/messages/edit.html.erb
<%= turbo_frame_tag "new_message" do %>
  <div class="flex items-center">
      <div class="flex items-center bg-slate-800 rounded-lg  p-2">
          <p class="truncate max-w-50 text-white"><%= @message.content %></p>
          <%= link_to 'Destroy', chat_message_path(@chat, @message), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: 'mx-2 underline text-red-500 text-sm font-semibold' %>
      </div>

      <%= link_to "Cancel", chat_messages_url(@chat), class: "text-yellow-500 text-sm font-semibold ml-2" %>
  </div>

  <%= render "form", { chat: @chat, message: @message } %>
<% end %>

app/views/messages/index.html.erb
<div data-current-user="<%= Current.user.name %>" hidden></div>

<% content_for :title, "Messages" %>

<div data-controller='scroll'>
    <div class='fixed top-20 flex justify-start items-center space-x-2'>
        <% if @participant.avatar.attached? %>
            <%= link_to image_tag(@participant.avatar, class: 'border-3 border-blue-600 object-cover rounded-full min-w-14 max-w-14 h-14'), identity_profile_path(@participant.name) %>
        <% else %>
            <div class="bg-gray-600 border-3 border-blue-600 object-cover rounded-full min-w-14 max-w-14 h-14"></div>
        <% end %>

        <h1 class="text-lg"><%= @participant.name %></h1>
    </div>

    <%= turbo_stream_from @chat %>
    <div id="messages" data-chat-id="<%= @chat.id %>" class="flex flex-col-reverse mb-22 mt-18">
        <%= render partial: "messages/message", locals: { chat: @chat }, collection: @page.records, as: :message %>
        <%= render "layouts/next_page_container", src: chat_messages_path(chat: @chat, page: @page.next_param, format: :turbo_stream) unless @page.last? %>
    </div>

    <div class="fixed bottom-4 container pr-10">
        <div class="mb-6 text-right">
            <button data-scroll-target="scrollButton" data-action="click->scroll#scrollToEnd" class="font-bold bg-black text-white rounded-full p-2">
                <svg class="w-3 h-3 text-right" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
                </svg>
            </button>
        </div>

        <%= turbo_frame_tag "new_message" do %>
            <%= render "form", { chat: @chat, message: @chat.messages.build } %>
        <% end %>
    </div>
</div>

app/views/messages/index.turbo_stream.erb
<%= turbo_stream.replace :next_page_container, partial: "messages/message", locals: { chat: @chat }, collection: @page.records, as: :message %>

<% unless @page.last? %>
  <%= turbo_stream.append :messages, partial: "messages/next_page_container", locals: { page: @page.next_param } %>
<% end %>