config/routes.rb
Rails.application.routes.draw do
  resources :registrations, only: %i[ new create ]

  resources :sessions, only: %i[ index new create destroy ]

  resources :passwords, param: :token

  namespace :identity do
    resources :profiles, param: :name, only: %i[ index show ]
    resources :accounts, only: %i[ show edit update ]
    resources :avatars,  only: %i[ edit update destroy ]
    resources :tags,     except: %i[ index show ]
  end

  post "chats/:guest", to: "chats#create", as: :create_chat
  resources :chats, only: %i[ index destroy ] do
    resources :messages, except: %i[ new show ]
  end

  root "chats#index"
end

app/views/layouts/_navbar.html.erb
<nav class="sticky top-0 border-t-3 border-black bg-white dark:bg-slate-600 shadow-sm mb-12 z-10">
  <div class="container mx-auto p-3 flex flex-wrap items-center justify-between">
    <h1>
      <%= link_to 'Nexus', root_path, class: 'text-2xl font-bold bg-gradient-to-r from-blue-500 to-black dark:to-white inline-block text-transparent bg-clip-text' %>
    </h1>
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center justify-center text-md focus:text-orange-600 md:hidden" aria-controls="navbar-default" aria-expanded="false">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-7">
          <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5M12 17.25h8.25" />
        </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-300 rounded-lg md:flex-row md:space-x-2 rtl:space-x-reverse md:mt-0 md:border-0">
        <li>
          <%= link_to 'Home', root_path, class: 'block py-2 px-3 text-blue-500 bg-blue-200 rounded-sm md:bg-transparent hover:bg-blue-200 md:py-2 md:px-3'%>
        </li>
        <% if authenticated? %>
            <li>
              <%= link_to 'Chats', chats_path, class: 'block py-2 px-3 rounded-sm hover:bg-gray-200 hover:text-black md:py-2 md:px-3' %>
            </li>
            <li>
              <%= link_to 'Profiles', identity_profiles_path, class: 'block py-2 px-3 rounded-sm hover:bg-gray-200 hover:text-black md:py-2 md:px-3' %>
            </li>
            <li>
              <%= link_to 'Account', identity_account_path(Current.user), class: 'block py-2 px-3 rounded-sm hover:bg-gray-100 hover:text-black md:py-2 md:px-3' %>
            </li>
            <li>
              <%= button_to 'Log out', Current.session, method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: 'block py-2 px-3 text-red-600 rounded-sm bg-red-100 md:py-2 md:px-3' %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_next_page_container.html.erb
<%= turbo_frame_tag :next_page_container, loading: :lazy, src: src, class: "flex justify-center my-4" do %>
    <svg aria-hidden="true" class="mt-6 inline w-8 h-8 text-gray-200 animate-spin dark:text-white fill-indigo-600" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"/>
        <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"/>
    </svg>
  <span class="sr-only">Loading...</span>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Nexus" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">


    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


  <body class="bg-white dark:bg-gray-700 dark:text-white" data-controller='theme'>
    <%= render 'layouts/navbar' %>

    <main class="container mx-auto px-5">
      <%= yield %>
    </main>
  </body>
</html>